name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main  # Adjust this as necessary for your main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '20'  # Adjust as necessary
    - name: Install Dependencies
      run: npm install  # If your project has dependencies
    - name: Build
      run: npm run build  # If your project needs a build step
    - name: Deploy to Firebase
      run: firebase deploy --only hosting --token ${{ secrets.FIREBASE_TOKEN }}
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}